model:
  n_hidden: 1024
  learning_rate: 0.001
  batch_size: 64
  epochs: 50
  k: 10

data:
  holdout_ratio: 0.1
  min_likes_user: 50
  min_likes_anime: 50

paths:
  model_path: "out/rbm_best_model.pth"
  output_csv: "out/recommendations.csv"
